CREATE DATABASE `ROMTECH`;

CREATE TABLE `users` (
id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(30) NOT NULL,
password VARCHAR(255) NOT NULL,
first_name VARCHAR(25),
last_name VARCHAR(25),
modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

